# Generated by Django 4.1 on 2022-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
